### ISSUE TITLE
Not installing?

### ISSUE THREAD

**Issue by Bubbler670** [SirFaizdat/Prison#81]
when I try to install it, the plugin shoes up in the plugins directory but there is no folder and I have world edit, world guard, and essentials. Also when I type /plugins all my plugins show up except that one. Anyone got any responses?

**Comment by SirFaizdat** [comment]
Make sure you have Vault installed. If that doesn't help, please send me the error message from your server's console.

**Comment by Bubbler670** [comment]
theres no error in the console, just there is no folder when I installed it as well as the in game the command /rankup or /mines doesn't work as well as /plugins it doesn't show it in there I don't think its registering in the server

**Comment by SirFaizdat** [comment]
There should definitely be an error in the console, because it's not registering. The error should be even before the worlds load. But before doing that, *make sure you have Vault and WorldEdit*

**Comment by Bubbler670** [comment]
can I have you join the server and see for yourself?

**Comment by Bubbler670** [comment]
I GOT IT! Caused by: java.lang.UnsupportedClassVersionError: me/sirfaizdat/prison/core/Prison : Unsupported major.minor version 52.0

**Comment by Bubbler670** [comment]
uhhhhh what does that mean?

**Comment by SirFaizdat** [comment]
For some reason Prison is trying to use Java 1.8 (52.0) instead of Java 1.7 (51.0). This build should fix it, although I haven't really tested it. Try it out and let me know :)

https://www.dropbox.com/s/19pna3v1s9ugb3h/Prison.jar?dl=0

**Comment by Bubbler670** [comment]
it still doesn't work

Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
ERROR Could not load 'plugins/Prison.jar' in folder 'plugins'

**Comment by SirFaizdat** [comment]
Alright, I'll get on a more in-depth fix soon.

**Comment by Bubbler670** [comment]
ok thank you :) let me know when you get it fixed!

**Comment by SirFaizdat** [comment]
https://www.dropbox.com/s/67zsrse9i58vmz7/Prison.jar?dl=0

That one should work, I made a tiny mistake with the code xD Try it now and see how it goes.

**Comment by Bubbler670** [comment]
Ok it now shows in /plugins! but I cant type commands and this error occurred

Error occurred while enabling Prison v2.2-SNAPSHOT (Is it up to date?)

**Comment by SirFaizdat** [comment]
It's compatible with everything (all Bukkit plugins work with Spigot). There should be more error than just that, and also, make sure you have all the dependencies (Vault and WorldEdit).

**Comment by Bubbler670** [comment]
I have WE and Vault and that's my 1 and only error in the console :/ sorry

**Comment by Bubbler670** [comment]
oops

**Comment by SirFaizdat** [comment]
I think I know what the problem is and I'll have a patch for you to test out by tomorrow :)

**Comment by Bubbler670** [comment]
yay! ok thank you so much!

**Comment by SirFaizdat** [comment]
Try this and see how it goes:
https://www.dropbox.com/s/67zsrse9i58vmz7/Prison.jar?dl=0

**Comment by AlliedCore** [comment]
^ Genius

**Comment by Bubbler670** [comment]
IT WORKS THANK U SO MUCH!!!!!!!!!!!!!!!!!!!!
